[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
board_upload.flash_size = 4MB
board_build.partitions = default.csv

build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DPIEZO_PIN=1
  -DLED_PIN=21
  -DUSE_NEOPIXEL_LED=1
