#pragma once

#include <lvgl.h>

// Generated by tools/generate_weather_icon_assets.py

extern const lv_img_dsc_t gWeatherIcon88ClearDay;
extern const lv_img_dsc_t gWeatherIcon88ClearNight;
extern const lv_img_dsc_t gWeatherIcon88PartlyCloudyDay;
extern const lv_img_dsc_t gWeatherIcon88PartlyCloudyNight;
extern const lv_img_dsc_t gWeatherIcon88Overcast;
extern const lv_img_dsc_t gWeatherIcon88Fog;
extern const lv_img_dsc_t gWeatherIcon88Drizzle;
extern const lv_img_dsc_t gWeatherIcon88Rain;
extern const lv_img_dsc_t gWeatherIcon88Snow;
extern const lv_img_dsc_t gWeatherIcon88Thunderstorms;
extern const lv_img_dsc_t gWeatherIcon88Unknown;

extern const lv_img_dsc_t gWeatherIcon48ClearDay;
extern const lv_img_dsc_t gWeatherIcon48ClearNight;
extern const lv_img_dsc_t gWeatherIcon48PartlyCloudyDay;
extern const lv_img_dsc_t gWeatherIcon48PartlyCloudyNight;
extern const lv_img_dsc_t gWeatherIcon48Overcast;
extern const lv_img_dsc_t gWeatherIcon48Fog;
extern const lv_img_dsc_t gWeatherIcon48Drizzle;
extern const lv_img_dsc_t gWeatherIcon48Rain;
extern const lv_img_dsc_t gWeatherIcon48Snow;
extern const lv_img_dsc_t gWeatherIcon48Thunderstorms;
extern const lv_img_dsc_t gWeatherIcon48Unknown;
