#!/usr/bin/env python3
"""Generate LVGL PNG image descriptors for dashboard weather icons.

Source icon set:
  Meteocons / weather-icons by Bas Milius (MIT)
  https://github.com/basmilius/weather-icons
"""

from __future__ import annotations

import pathlib
import subprocess
import urllib.request


ROOT = pathlib.Path(__file__).resolve().parents[1]
SVG_DIR = ROOT / "assets" / "weather" / "svg"
PNG_88_DIR = ROOT / "assets" / "weather" / "png" / "88"
PNG_48_DIR = ROOT / "assets" / "weather" / "png" / "48"
OUT_HEADER = ROOT / "src" / "ui" / "assets" / "WeatherPngAssets.h"
OUT_SOURCE = ROOT / "src" / "ui" / "assets" / "WeatherPngAssets.cpp"
ATTRIBUTION = ROOT / "assets" / "weather" / "ATTRIBUTION.txt"


ICONS = [
    ("ClearDay", "clear-day"),
    ("ClearNight", "clear-night"),
    ("PartlyCloudyDay", "partly-cloudy-day"),
    ("PartlyCloudyNight", "partly-cloudy-night"),
    ("Overcast", "overcast"),
    ("Fog", "fog"),
    ("Drizzle", "drizzle"),
    ("Rain", "rain"),
    ("Snow", "snow"),
    ("Thunderstorms", "thunderstorms"),
    ("Unknown", "not-available"),
]

CDN_BASE = "https://cdn.jsdelivr.net/gh/basmilius/weather-icons/production/fill/all"


def ensure_dirs() -> None:
    for path in (SVG_DIR, PNG_88_DIR, PNG_48_DIR, OUT_HEADER.parent):
        path.mkdir(parents=True, exist_ok=True)


def download_svg(icon_slug: str) -> pathlib.Path:
    out_path = SVG_DIR / f"{icon_slug}.svg"
    url = f"{CDN_BASE}/{icon_slug}.svg"
    with urllib.request.urlopen(url, timeout=20) as response:
        data = response.read()
    out_path.write_bytes(data)
    return out_path


def render_png(svg_path: pathlib.Path, png_path: pathlib.Path, size: int) -> None:
    subprocess.run(
        ["rsvg-convert", "-w", str(size), "-h", str(size), str(svg_path), "-o", str(png_path)],
        check=True,
    )


def format_c_bytes(data: bytes, indent: str = "  ", width: int = 16) -> str:
    lines: list[str] = []
    for i in range(0, len(data), width):
        chunk = data[i : i + width]
        byte_text = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"{indent}{byte_text},")
    return "\n".join(lines)


def write_header() -> None:
    lines = [
        "#pragma once",
        "",
        '#include <lvgl.h>',
        "",
        "// Generated by tools/generate_weather_icon_assets.py",
        "",
    ]
    for name, _ in ICONS:
        lines.append(f"extern const lv_img_dsc_t gWeatherIcon88{name};")
    lines.append("")
    for name, _ in ICONS:
        lines.append(f"extern const lv_img_dsc_t gWeatherIcon48{name};")
    lines.append("")
    OUT_HEADER.write_text("\n".join(lines))


def descriptor_block(var_name: str, png_name: str, width: int, height: int, png_bytes: bytes) -> str:
    arr = format_c_bytes(png_bytes)
    return (
        f"static const uint8_t {png_name}[] = {{\n"
        f"{arr}\n"
        "};\n\n"
        f"const lv_img_dsc_t {var_name} = makeRawPngDsc({png_name}, {len(png_bytes)}, {width}, {height});\n"
    )


def write_source() -> None:
    blocks: list[str] = []
    header = [
        '#include "ui/assets/WeatherPngAssets.h"',
        "",
        "// Generated by tools/generate_weather_icon_assets.py",
        "",
        "namespace {",
        "lv_img_dsc_t makeRawPngDsc(const uint8_t* data, uint32_t dataSize, uint16_t width, uint16_t height) {",
        "  lv_img_dsc_t dsc = {};",
        "  dsc.header.always_zero = 0;",
        "  dsc.header.w = width;",
        "  dsc.header.h = height;",
        "  dsc.header.cf = LV_IMG_CF_RAW_ALPHA;",
        "  dsc.data_size = dataSize;",
        "  dsc.data = data;",
        "  return dsc;",
        "}",
        "}  // namespace",
        "",
    ]

    for name, slug in ICONS:
        png88 = (PNG_88_DIR / f"{slug}.png").read_bytes()
        png48 = (PNG_48_DIR / f"{slug}.png").read_bytes()
        blocks.append(descriptor_block(f"gWeatherIcon88{name}", f"kWeatherIcon88{name}Png", 88, 88, png88))
        blocks.append(descriptor_block(f"gWeatherIcon48{name}", f"kWeatherIcon48{name}Png", 48, 48, png48))

    OUT_SOURCE.write_text("\n".join(header + blocks))


def write_attribution() -> None:
    ATTRIBUTION.write_text(
        "\n".join(
            [
                "Weather icon source:",
                "Meteocons / weather-icons by Bas Milius",
                "https://github.com/basmilius/weather-icons",
                "License: MIT",
                "",
                "Icons downloaded from:",
                f"{CDN_BASE}/",
                "",
                "Generated sizes: 88x88 and 48x48 PNG",
            ]
        )
        + "\n"
    )


def main() -> None:
    ensure_dirs()
    for _, slug in ICONS:
        svg = download_svg(slug)
        render_png(svg, PNG_88_DIR / f"{slug}.png", 88)
        render_png(svg, PNG_48_DIR / f"{slug}.png", 48)
    write_header()
    write_source()
    write_attribution()
    print(f"Generated: {OUT_HEADER}")
    print(f"Generated: {OUT_SOURCE}")


if __name__ == "__main__":
    main()
